#!/bin/bash

#
# This is a Linux script, best run on mast-wis-control.
# It dumps the MAST configuration database into config-db.json, which can be used in case there's
#  no connection to the MongoDB
#
# It produces the file mast-config-db.json which, if copied to 'C:/MAST/mast-config-db.json' can act as 
#  a configuration DB surrogate.
#

DB=mast
mkdir -p export
for c in $(mongosh --quiet --eval "db.getSiblingDB('$DB').getCollectionNames().join(' ')"); do
  if [ "${c}" = users ]; then
    continue
  fi
  mongoexport --db "$DB" --collection "$c" --pretty --jsonArray > export/${c}.json 2>/dev/null
done

jq -n 'reduce inputs as $in ({}; .[(input_filename | gsub("^.*[\\\\/]+"; "") | rtrimstr(".json"))] = $in)' export/*.json > mast-config-db.json

/bin/rm -rf export
