[task]
quorum = 1
ulid = "01jj6rzhvkve6ta6xj9jm4cjpw"
file = "C:/Users/mast/PycharmProjects/MAST_spec/common/tasks/assigned_highspec_task.toml"

#
# Valid ways of specifiying unit assignments
#
# - [unit.w]: specifies a single unit, named 'w' at the local site ('wis')
# - [unit.'wis:w ns:north:2 ns:2-5,7,8-10 nam:17']: specifies a set of units which includes
#   - the unit named 'w' at site named 'wis'
#   - unit '2' at site 'ns' (Neot Smadar) in the 'north' building
#   - units '2' to '5', '7', and '8' to '10' at 'ns' (Neot Smadar)
#   - unit '17' at site 'nam' (Namibia)
#
# NOTE(s):
#  - more than one 'unit' specifiers are allowed, each with (potentially, but not mandatory) its own target
#
[unit.w]
ra = '12:34:56.789'
dec = -23.45

[spec]
instrument = 'highspec'
exposure = 12.5

[spec.camera]
binning = { x=1, y=2  }
temperature = { set_point = -15 }
shutter = {opening_time = 20, closing_time = 30}
gain = 150

[spec.calibration]
lamp_on = true
filter = 'ND4000'
