[task]
name = 'Sample deepspec assigned task'
quorum = 1
ulid = "01jj6rzhvkve6ta6xj9jm4cjpw"
file = "C:/Users/mast/PycharmProjects/MAST_spec/common/tasks/assigned_deepspec_task.toml"

#
# Valid ways of specifiying unit assignments
#
# - [unit.w]: specifies a single unit, named 'w' at the local site ('wis')
# - [unit.'wis:w ns:north:2 ns:2-5,7,8-10 nam:17']: specifies a set of units which includes
#   - the unit named 'w' at site named 'wis'
#   - unit '2' at site 'ns' (Neot Smadar) in the 'north' building
#   - units '2' to '5', '7', and '8' to '10' at 'ns' (Neot Smadar)
#   - unit '17' at site 'nam' (Namibia)
#
# NOTE(s):
#  - more than one 'unit' specifiers are allowed, each with (potentially, but not mandatory) its own target
#
[unit.w]
ra = '12:34:56.789'
dec = -23.45

[spec]
instrument = 'deepspec'
exposure = 12.5

[spec.camera]
binning = { x = 2, y = 3 }

[spec.camera.U]
binning = { x = 1 }
crop = { col=200, line=100  }

[spec.camera.X]
binning = {x=1, y=2}

[spec.calibration]
lamp_on = true
filter = 'ND1000'
