[task]
name = 'Sample highspec assigned task'
quorum = 1
production = false

#
# Valid ways of specifiying unit assignments
#
# - [unit.w]: specifies a single unit, named 'w' at the local site ('wis')
# - [unit.'wis:w ns:north:2 ns:2-5,7,8-10 nam:17']: specifies a set of units which includes
#   - the unit named 'w' at site named 'wis'
#   - unit '2' at site 'ns' (Neot Smadar) in the 'north' building
#   - units '2' to '5', '7', and '8' to '10' at 'ns' (Neot Smadar)
#   - unit '17' at site 'nam' (Namibia)
#
# NOTE(s):
#  - more than one 'unit' specifiers are allowed, each with (potentially, but not mandatory) its own target
#
ulid = "01jknm5pwnyh5qys2nspx9g4fk"
file = "/Storage/mast-share/MAST/tasks/assigned/TSK_assigned_highspec_task.toml"
[unit.w]
ra = '12:34:56.789'
dec = -23.45

[spec]
instrument = 'highspec'
disperser = 'Ca'
exposure = 3
number_of_exposures = 3

[spec.camera]
binning = { x=1, y=2  }
temperature = { set_point = -15 }
shutter = {opening_time = 20, closing_time = 30}
em_gain = 253
pre_amp_gain = 0    # can be 0, 1 or 2

[spec.calibration]
lamp_on = true
filter = 'ND4000'

[constraints.moon]
max_phase = 10
# min_distantance = 30 # [deg]

[constraints.seeing]
# max = 3.5

#[constraints.time_window]
# start =
# end =

[[events]]
when = "2025-02-11T10:13:31.530338"
what = "created"

[[events]]
when = "2025-02-11T10:50:46.570124"
what = "created"
